apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ycd51v3ua-go
  janus-idp.io/tekton: ycd51v3ua-go
  backstage.io/kubernetes-id: ycd51v3ua-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ycd51v3ua-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
