apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ycd51v3ua-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ycd51v3ua-go 
  name: ycd51v3ua-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ycd51v3ua-go 
